### ISSUE TITLE
make all tests pass

### ISSUE THREAD

**Issue by edgarcosta** [roed314/lmfdb_postgres#11]
If we ignore Belyi and Abvar, we have 2 failures:

### torsion structure see #39 
- http://localhost:37777/EllipticCurve/Q/?start=0&conductor=&jinv=&rank=&torsion=&torsion_structure=[7]&sha=&optimal=&surj_primes=&surj_quantifier=include&nonsurj_primes=&count=100

- http://localhost:37777/EllipticCurve/Q/?conductor=&jinv=&rank=&torsion=&torsion_structure=%5B2%2C4%5D&sha=&surj_primes=&surj_quantifier=include&nonsurj_primes=&optimal=&count=100

- abvar #3 
- Belyi  #14

**Comment by edgarcosta** [comment]
- localhost:3777/GaloisGroup/?start=0&paging=0&parity=-1&cyc=0&solv=1&prim=-1&n=&t=18&count=50

**Comment by roed314** [comment]
All tests pass!
