### ISSUE TITLE
Small group knowls

### ISSUE THREAD

**Issue by roed314** [roed314/lmfdb_postgres#19]
[localhost:37777/knowledge/show/group.small.data?gapid=2.1](http://localhost:37777/knowledge/show/group.small.data?gapid=2.1)
vs
[beta.lmfdb.org/knowledge/show/group.small.data?gapid=2.1](http://beta.lmfdb.org/knowledge/show/group.small.data?gapid=2.1)

**Comment by edgarcosta** [comment]
other dynamic knowls:
http://localhost:37777/knowledge/show/gg.character_table.data
