### ISSUE TITLE
Download stored data link on ECNF pages broken

### ISSUE THREAD

**Issue by edgarcosta** [roed314/lmfdb_postgres#35]
Drew

> The code download links work, and the download all store data links on 
> EC/Q seem to work, but if you got to an ECNF page and click download all 
> stored data you get a server error, e.g.
> http://legendre.mit.edu/EllipticCurve/download_all/2.0.4.1/25.1/CMa/1

David

> This is easy to fix, but I have a related design question first.
> 
> We're now using custom json encoding for some things.  For example, we store a real literal 1.0123456789 using the dictionary {"__RealLiteral__": 0, "data": "1.0123456789", "prec": 53}.  This allows us to losslessly encode and decode data when interacting with the database.  Should we use the same format for downloads?  Just a string?  A float, with possible precision loss?

**Comment by roed314** [comment]
Fixed
