### ISSUE TITLE
torsion structure of EC should be stored list of integers?

### ISSUE THREAD

**Issue by edgarcosta** [roed314/lmfdb_postgres#39]
this makes queries like this fail:
http://postgres.lmfdb.xyz/EllipticCurve/Q/?torsion_structure=%5B2%2C2%5D&surj_quantifier=include&count=100
vs
http://beta.lmfdb.xyz/EllipticCurve/Q/?torsion_structure=%5B2%2C2%5D&surj_quantifier=include&count=100

However, that is how they are stored originally in mongo:
http://beta.lmfdb.xyz/api/elliptic_curves/curves/?_delim=%3B&torsion_structure=ls2%3B2

ps, if we change how we store them, we should fix the api example and test
http://postgres.lmfdb.xyz/api/ec_curves/

**Comment by AndrewVSutherland** [comment]
For elliptic curves over number fields the torsion structure is stored as a list of integers.  We may as well make elliptic curves over Q the same.

**Comment by roed314** [comment]
Done.
