### ISSUE TITLE
Galois group wrong in local algebas section for number fields 

### ISSUE THREAD

**Issue by roed314** [roed314/lmfdb_postgres#49]
In the table at the bottom of http://legendre.mit.edu/NumberField/12.0.9432741934268416.1, the Galois group entries are wrong (compare with http://lmfdb.org/NumberField/12.0.9432741934268416.1)

**Comment by edgarcosta** [comment]
This is a data issue.
Somehow, `'gal': [6, 3], 'galT': 3` got converted to `'gal': 3, 'galT': 3` instead of `'gal': 6, 'galT': 3`.

See:
* http://www.lmfdb.org/api/localfields/fields/?label=s2.6.11.9

* http://postgres.lmfdb.xyz/api/lf_fields/?label=s2.6.11.9

**Comment by roed314** [comment]
Fixed
