### ISSUE TITLE
Investigate large memory usage

### ISSUE THREAD

**Issue by roed314** [roed314/lmfdb_postgres#50]
Queries were slow because legendre was running out of memory.

**Comment by edgarcosta** [comment]
@AndrewVSutherland , I think postgres just triggers a lot of cache.


Here is proddb at the moment (after running tests on it)
```
edgarcosta@proddb:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          30151         384         946         139       28820       29183
Swap:             0           0           0
```
28 GB cached, but only 384 mb used.

**Comment by edgarcosta** [comment]
We should wait one more week to see if cache overwhelms the system again, but so far it looks stable: http://legendre.mit.edu/munin/PostgreSQL/legendre/memory.html

**Comment by edgarcosta** [comment]
Two things, the memory usage on legendre is under control:

http://legendre.mit.edu/munin/PostgreSQL/legendre/memory.html

However, the proddb server keeps using more and more cache:

http://legendre.mit.edu/munin/PostgreSQL/proddb/memory.html

Will see if the this stabelizes

**Comment by edgarcosta** [comment]
I think I understand this now, and I don't think is an issue anymore.

1-  the cache we observed, it was all disk cache.
2- we were using the default values for:

- `shared_buffers`: how much memory is dedicated to PostgreSQL to use for caching data.
- `effective_cache_size`: an estimate of how much memory is available for disk caching by the operating system and within the database itself

and these values are very low, and these affect the planner.

3- Now, with these properly set in all the 3 servers, queries are working as expected.

For example, before difficult queries were timing out on web.lmfdb.xyz, but after reconfiguring the server, these run without an issue, and the free memory is below 1GB.
