### ISSUE TITLE
knowl pages not showing on web.lmfdb.xyz

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/lmfdb_postgres#74]
On web.lmfdb.xyz knowl pop ups work fine, but attempting to access knowl home pages generates on error, e.g.

http://web.lmfdb.xyz/knowledge/show/g2c.igusa_clebsch_invariants

whereas

http://dev.lmfdb.xyz/knowledge/show/g2c.igusa_clebsch_invariants

works fine.

**Comment by edgarcosta** [comment]
Very weird. I will look into the logs

**Comment by edgarcosta** [comment]
Fixed. By mistake, I was revoking SELECT on the schema userdb from the user webserver.
