### ISSUE TITLE
Elliptic curve 1-99 link on dev.lmfdb.xyz broken

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/lmfdb_postgres#82]
http://web.lmfdb.xyz/EllipticCurve/Q/?conductor=1-99 works but
http://dev.lmfdb.xyz/EllipticCurve/Q/?conductor=1-99 is broken

I believe this was caused by the most recent PR that was merged

**Comment by edgarcosta** [comment]
This is a database issue. Everything goes well if we connect to proddb. We might be missing some indexes.

**Comment by edgarcosta** [comment]
It looks like this might be`resort` that is taking too long. 
We are looking into it.

**Comment by JohnCremona** [comment]
This is working now on dev.
