### ISSUE TITLE
download requires an extra click that is unnecessary in many cases

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/lmfdb_postgres#85]
Downloading, say, the list of elliptic curves with conductor 11 requires one more click than it ideally should.  If you run the search

http://web.lmfdb.xyz/EllipticCurve/Q/?conductor=11&surj_quantifier=include&count=100

it will tell you there are 3 results.  But in order to download them you have to first click on a "determine the number of results" link (in order to again determine that there are 3 results).

**Comment by roed314** [comment]
Fixed (5 character typo in the relevant template).

**Comment by AndrewVSutherland** [comment]
Are you going to submit a PR for this?

**Comment by edgarcosta** [comment]
I have just submitted a PR where David fixed this (and I fixed some other
bug):
https://github.com/LMFDB/lmfdb/pull/2590
